# default values
all:
  sf_guard_plugin:
    # We register our own URLs that we like better.
    # Also we don't use the default admin gen modules
    # (Apostrophe comes with a more convenient set)
    routes_register: false
  a:
    page_cache_enabled: false
    # Only look at the best 500 search results. This saves enormous amounts of memory.
    # However Apostrophe does further filtering on these results so if the majority of
    # your pages are not visible to a particular user who is searching they may not
    # get some results they should have seen. You can address that by increasing this
    # limit or commenting it out. This is a design limitation that comes into play
    # whenever you combine two databases (Zend Lucene and MySQL) and criteria span
    # the two. Lucene makes matters worse by not providing any way to un-hydrate a
    # search result once you've peeked at it
    search_hard_limit: 500
    
    # Use array hydration for everything retrieved with a page object except
    # for the slots themselves, which we do hydrate as objects. 20-25% speed improvement
    fasthydrate: true

    routes_register: false
    default_on: true
    pretty_english_dates: true


    ### Apostrophe Credit Message
    credit: true                      # Give Apostrophe Credit "Built with Apostrophe"


    ### Apostrophe Pagination
    pager_nb_links: 5                 # How many pages to show in the pager between the scrolling arrows (Media, Blog, Events)


    ### Apostrophe Global Toolbar 
    persistent_global_toolbar: true   # Set to false if you want to hide the global toolbar to logged-out visitors
    
    global_button_order:              # (Re-order here to change the button order in the global toolbar)  
      - blog
      - events
      - media
      - categories
      - tags
      - users
      - reorganize

    i18n_switch: true                 # If true, there will be a language switcher in the Global Toolbar
    i18n_languages:                   # List of supported languages for populating the dropdown menu
      - en
      - fr
      - de
      - es
      - ru

    ### Integrated Third Party Services
    # You must acquire API keys from each service for them to work    
    # vimeo:                          # Vimeo API Key for Media Library
    #   oauthConsumerKey:
    #   oauthConsumerSecret:
    # viddler:                        # Viddler API Key for Media Library
    #   apiKey:
    # slideshare:                     # Slideshare API Key for Media Library
    #   apiKey:
    #   sharedSecret:
    # soundcloud:                     # SoundCloud API Key for Media Library
    #   consumerKey:

    <?php if (file_exists(dirname(__FILE__) . '/punk-demo-app.yml')) require dirname(__FILE__) . '/punk-demo-app.yml' ?>


    ### Apostrophe Permissions
    # Make sure you specify the candidate and sufficient groups for both managing
    # (that is, deleting and creating) and editing pages. It's typical to use the same
    # group of candidates for editors and managers, because you can still assign actual
    # managing and editing privileges for any individual page and its descendants via the
    # page settings dialog even if the pool of candidates is all one group
    manage_candidate_group: editor
    manage_sufficient_group: admin
    edit_candidate_group: editor
    edit_sufficient_group: admin

    # Permission to view locked pages. In our recommended fixtures,
    # the guest, editor and admin groups have this. Users that have no
    # group membership do not. If you want to give people "off the street" accounts,
    # this is a useful way to avoid giving them access to locked pages until they
    # are deemed worthy of membership in the guest group. If you comment out
    # this line, any authenticated user will be able to view locked pages
    view_locked_sufficient_credentials: view_locked


    ### Apostrophe Bundled Global Layout 
    use_bundled_layout: false                 # Set to true to use the layout file bundled with Apostrophe

    ### Apostrophe Site Title
    title_prefix: 'Apostrophe Sandbox | '
    title_suffix: ''

    ### Apostrophe Pages 
    # Sets a limit on the depth of the Apostrophe page tree for the site.
    # (e.g. page_level: 1 means the site can only have pages that are
    # peers to the homepage peers A.K.A. top navigation pages)
    # max_page_levels: 3

    # Sets a limit on the width of the Apostrophe Page tree for the site.
    # Specify the maximum number of child pages allowed to be created at any given level
    # max_children_per_page: 8

    templates:
      # "a:" contains "ordinary page templates"
      a:
        default: Default Page
        home: Home Page
      # This is how you enable engines as page type choices. If the 
      # engine supports alternate page templates you can specify more 
      # than one entry for an engine
      aMedia:
        default: Media
      aBlog:
        default: Blog
      aEvent:
        default: Events
      hHome:
        hHome: hHomePage
      hContact:
        hContact: hContactUsPage


    ### Apostrophe Slots
    slot_types:
      # aImage: Image                       # aImage slot was deprecated in favor of using aSlideshow slot

      aBlog: Blog Posts                     # apostropheBlogPlugin Slot
      aEvent: Events                        # apostropheBlogPlugin Slot

      aInsetImage: Inset Image              # apostropheExtraSlotsPlugin Slot
      aInsetArea: Inset Area                # apostropheExtraSlotsPlugin Slot
      aBlogSlideshow: Blog Slideshow        # apostropheExtraSlotsPlugin Slot
      aMap: Map                             # apostropheExtraSlotsPlugin Slot

      # The following slot types are always enabled (meaning only that you can include them in
      # individual templates if you wish, so you still have control over what your end users do):
      # aRichText
      # aText
      # aImage
      # aSlideshow
      # aButton
      # aAudio
      # aVideo
      # aPDF
      # aRawHTML
      #
      # You can enable additional slot types implemented at the application level or via
      # plugins by adding their type names here along with a short descriptive label.
      #
      # Example:
      # baseball: "Baseball Box Score"


    ### Apostrophe Slot Variants
    slot_variants:
      aSlideshow:
        normal:
          label: Normal
          options:
            arrows: true
        autoplay:
          label: Autoplay
          options:
            interval: 4
            arrows: false
      # aInsetArea is part of the apostropheExtraSlotsPlugin      
      aInsetArea:                       
        topLeft:
          label: Left Aligned
          options:
            insetTemplate: topLeft
        topRight:
          label: Right Aligned
          options:
            insetTemplate: topRight
      # aInsetImage is part of the apostropheExtraSlotsPlugin
      aInsetImage:                      
        topLeft:
          label: Left Aligned
          options:
            insetTemplate: topLeft
        topRight:
          label: Right Aligned
          options:
            insetTemplate: topRight


    ### Adding New Slots 
    # new_slots_top: false     # By default new slots in an area go to the top, set to FALSE to add new slots to the bottom of the page


    #### Slot & Area Buttons
    addslot_button_style: big                   # Button Classes output in Apostrophe Area and Slot Buttons: Add Slot, History, or Delete
    history_button_style: no-label big          # Button Classes output in Apostrophe Area and Slot Buttons: Add Slot, History, or Delete
    delete_button_style: no-label               # Button Classes output in Apostrophe Area and Slot Buttons: Add Slot, History, or Delete


    #### Apostrophe Styles & Javascript 
    # Minifier will allow you to group assets together
    asset_group: global                       # Default group for minifier assets

    # Disable ALL bundled CSS and JavaScript. Not recommended. See below for a more selective approach.
    # use_bundled_stylesheets: false          
    # use_bundled_javascripts: false

    # Selectively disable or override various bundled styles and javascripts.
    # Everything you leave alone or set to true loads by default
    # Uncomment below to disable the styles for that section
    use_bundled_stylesheets:
      reset: /apostrophePlugin/css/a-reset.less
      admin: /apostrophePlugin/css/a-admin.less
      forms: /apostrophePlugin/css/a-forms.less
      components: /apostrophePlugin/css/a-components.less
      engines: /apostrophePlugin/css/a-engines.less
      area-slots: /apostrophePlugin/css/a-area-slots.less
      buttons: /apostrophePlugin/css/a-buttons.less
      colors: /apostrophePlugin/css/a-colors.less
      utility: /apostrophePlugin/css/a-utility.less

       # OR, to override a specific stylesheet with a different one:
       # engines: /foo/bar.css

    # Uncomment below to disable the Javascripts for that section
    # (not recommended) or override them with a different release
    # (probably OK for a new jquery release for instance)

    # use_bundled_javascripts:
      # To turn one off uncomment it...
      # jquery: false
      # main: false
      # controls: false
      # json2: false
      # jquery-autogrow: false
      # jquery-hover-intent: false
      # jquery-ui: false
      # tagahead: false

      # To override one set a different path instead of false
      # jquery: /js/myjquery.js

  aAdmin:
    web_dir: /apostrophePlugin

  aMedia:
    # If not set, the same site is assumed
    # client_site: "http://www.mymediasite.com/"
    # You should change this both here and below
    client_apikey: 'dummy'
    apikeys:
      - 'dummy'
    apipublic: false
    admin_credential: media_admin
    upload_credential: media_upload
    use_bundled_layout: false
    embed_codes: true

  aEvents:
    display_calendar: true

  aBlog:
    link_author: true
    # Disqus Comments
    # Once you have a Disqus account, enable comments and put in your Disqus shortname
    # disqus_enabled: true
    # disqus_shortname: yourdisqusshortname

    # enable this if you are developing locally to see comments
    # disqus_developer: true

  aFeedback:
    email_auto: apostrophe@punkave.com
    email_manual: apostrophe@punkave.com
    # If not specified, same as email_auto. The email_manual address is suggested via a mailto: link if the automatic feedback form somehow fails
    # May have to be different at some point depending on your agreement with Akismet
    # akismet_siteurl:  'http://yourdomain' # Optional
    # akismet_apikey:   'yourkey'           # Optional

  aToolkit:
    indexes:
      - 'aPage'
      - 'aMediaItem'
    # RichText is passed through a clean-up method that accepts parameters for cleaning Tags, Attributes, and Styles per tag
    # Example declarations exist below. Take care when enabling these parameters
    # allowed_tags: [h3, h4, h5, h6, blockquote, p, a, ul, ol, nl, li, b, i, strong, em, strike, code, hr, br, div, table, thead, caption, tbody, tfoot, tr, th, td, pre, dl, dd, dt]
    # allowed_attributes:
    #   a: [ href, name, target, class, style ]
    #   img: [ src, class, style ]
    #   th: [ colspan, style, width ]
    #   td: [ colspan, style, width ]
    #   table: [ align, class, style, width ]
    #   ul: [ class, style, type ]
    #   ol: [ class, style, start, type ]
    #   blockquote: [ class, style ]
    #   p: [ class, style ]
    # allowed_styles:
    #   a: [ 'margin', 'margin-left', 'margin-right' ]
    #   img: [ 'margin', 'margin-left', 'margin-right' ]
    #   td: [ 'margin', 'margin-left', 'margin-right' ]
    #   table: [ 'margin', 'margin-left', 'margin-right', 'width' ]
    #   ul: [ 'margin', 'margin-left', 'margin-right', 'list-style-type' ]
    #   ol: [ 'margin', 'margin-left', 'margin-right', 'list-style-type' ]
    #   blockquote: [ 'margin', 'margin-left', 'margin-right' ]
    #   p: [ 'margin', 'margin-left', 'margin-right' ]

  # options for sfSyncContentPlugin, used to sync the database and also
  # data files such as the media plugin's images and the search indexes.
  # You can extend this if you have more data file folders

  sfSyncContent:
    # The database is content, of course, but what else?
    content:
      # Almost always
      - "web/uploads"
      # If you use P'unk Avenue stuff
      - "data/a_writable"

  # For us this is the right place to find the netpbm utilities and ghostscript
  # (pnmtopng, gs, etc). Change it if your environment differs. Note that the
  # default PATH is still searched too, so on most production servers you can
  # leave this setting alone and not break it out separately for prod

  aimageconverter:
    path: /opt/local/bin
    # To force use of gd shut off netpbm
    # netpbm: false
    # To force use of netpbm set it to 'always'
    # netpbm: always
    # Default is to use gd for images under 1024x768 for performance reasons,
    # and because most (though not all) images with alpha channels (preserved by gd) are
    # that small or smaller

  # You need to set this to your site's hostname to use a:refresh to update
  # URLs in media slots etc

#  cli:
#    host: cmstest14

# In the production environment, we minify CSS and JS by default.
# We'd like to gzip them too, but a lot of people don't have the
# zlib extension in PHP. We encourage you to turn that on and see.
# If you don't have the zlib extension have your host/sysadmin fix that

# TODO: right now I have both turned on to demonstrate what this branch
# is all about, but a_minify_gzip needs turning off before this becomes
# the mainstream sandbox. We should always turn it on again when creating
# our own client sites

# WARNING: if you turn off all settings here for 'prod', COMMENT OUT the
# 'prod' and 'a' lines too or you will shut off ALL of your Apostrophe settings

prod:
  a:
    # Combines css and js files. You want this, because we use a lot of them
    minify: true
    # If you don't have the gzip extension in PHP or you don't have Apache configured
    # to cope with gzipped files, just set this false. If you do have those things
    # consider setting it true for even better front end performance
    minify_gzip: false
    # To add google analytics to a site, uncomment the following lines and add your analytics tracking code
    # Make sure you are including the googleAnalytics partial in your layout.php
    # googleAnalytics:
    #   account:
    #   domainName:

    # We symfony cc on each deploy, so we don't have to waste time checking
    # modification times of @imported less files and playing with sfFileCache
    less_check_dependencies: false

    # Cache all pages for 5 minutes for logged-out users
    # page_cache_enabled: true

# staging ought to be just like prod so we are not stunned and amazed
# by the behavior of prod

staging:
  a:
    # do_not_edit: true   # Quickly and easily display the 'Do Not Edit' message on staging sites after launch.
    minify: true
    # If you don't have the gzip extension in PHP or you don't have Apache configured
    # to cope with gzipped files, just set this false
    minify_gzip: false
    # We symfony cc on each deploy, so we don't have to waste time checking
    # modification times of @imported less files and playing with sfFileCache
    less_check_dependencies: false
    # Cache all pages for 5 minutes for logged-out users
    # page_cache_enabled: true

dev:
  a:
    js_debug: true